export const DEPT_CATEGORIES: Record<string, string[]> = {
  IT: [
    'Application Issue', 'Login & Authentication', 'Email Issue',
    'Network & Internet Issue', 'VPN Issue', 'System Performance Issue',
    'Hardware Issue', 'Software Installation', 'Printer & Scanner Issue',
    'Password Reset', 'Access Request', 'Security Incident',
    'API/Integration Issue', 'Bug Report', 'Other IT Issue',
  ],
  PRODUCT: [
    'New Feature Request', 'Product Enhancement', 'UI/UX Improvement',
    'Workflow Change', 'Business Rule Update', 'API Requirement',
    'Requirement Clarification', 'Configuration Change', 'Bug Validation',
    'Production Feature Issue', 'Product Feedback', 'Other Product Request',
  ],
  MARKETING: [
    'Campaign Creation', 'Campaign Approval', 'Creative Design Request',
    'Social Media Support', 'Content Writing', 'WhatsApp Campaign',
    'SMS Campaign', 'Email Campaign', 'Landing Page Request',
    'Brand Assets', 'SEO Request', 'Other Marketing Request',
  ],
  SALES: [
    'Lead Assignment', 'Lead Issue', 'Customer Follow-up',
    'Sales Report', 'Incentive Query', 'Sales CRM Issue',
    'Sales Material Request', 'Product Information', 'Sales Approval',
    'Customer Escalation', 'Other Sales Issue',
  ],
  CALLING: [
    'Dialer Issue', 'Call Not Connecting', 'Call Recording Issue',
    'CRM Calling Issue', 'Call Quality Issue', 'Headset Issue',
    'Disposition Issue', 'Calling Data Issue', 'Campaign Allocation',
    'Other Calling Issue',
  ],
  ACTIVATION: [
    'Customer Activation', 'KYC Pending', 'Document Verification',
    'Account Activation', 'Customer Verification', 'Activation Failed',
    'Activation Delay', 'Re-KYC', 'Activation Approval',
    'Other Activation Issue',
  ],
  IT_ADMIN: [
    'Laptop/Desktop Request', 'Asset Allocation', 'Asset Return',
    'Software License Request', 'Email Creation', 'User Access Creation',
    'Office Equipment Issue', 'Visitor Access', 'ID Card Request',
    'Employee Onboarding', 'Employee Offboarding', 'Other Admin Request',
  ],
  PROD_SUP: [
    'Production Bug', 'API Failure', 'Performance Issue',
    'Database Issue', 'Deployment Issue', 'Server Issue',
    'Payment Failure', 'Integration Failure', 'Incident Management',
    'Monitoring Alert', 'Hotfix Request', 'Root Cause Analysis',
    'Other Production Issue',
  ],
  LEGAL: [
    'Agreement Review', 'Legal Notice', 'Regulatory Compliance',
    'RBI Compliance', 'Audit Support', 'Vendor Agreement',
    'Customer Complaint', 'Policy Review', 'Documentation Review',
    'Compliance Approval', 'Other Legal Request',
  ],
  DATA: [
    'Data Extraction', 'Report Request', 'Dashboard Request',
    'SQL Query Request', 'Data Correction', 'Data Upload',
    'Data Validation', 'Data Mismatch', 'MIS Request',
    'Analytics Request', 'Other Data Request',
  ],
  OPERATIONS: [
    'Customer Query', 'Loan Disbursement', 'Repayment Issue',
    'Refund Request', 'NACH Issue', 'Collection Issue',
    'KYC Issue', 'Application Issue', 'Escalation',
    'Process Clarification', 'Vendor Coordination', 'Other Operational Issue',
  ],
  FINANCE: [
    'Vendor Payment', 'Employee Reimbursement', 'Invoice Processing',
    'Purchase Order', 'Budget Approval', 'Payment Failure',
    'Bank Reconciliation', 'GST Query', 'TDS Query',
    'Salary Issue', 'Expense Approval', 'Other Finance Issue',
  ],
  HR: [
    'Employee Onboarding', 'Employee Offboarding', 'Leave Request',
    'Attendance Issue', 'Payroll Query', 'Salary Issue',
    'Incentive Query', 'PF Query', 'ESIC Query',
    'Gratuity Query', 'Offer Letter Request', 'Experience Letter Request',
    'Relieving Letter Request', 'Employment Verification', 'ID Card Request',
    'HR Policy Clarification', 'Training Request', 'Performance Review',
    'Recruitment Request', 'Background Verification (BGV)',
    'Employee Complaint', 'Workplace Harassment', 'Employee Engagement',
    'Asset Handover Coordination', 'Other HR Request',
  ],
};
