# Generated by Django 6.0.6 on 2026-07-03 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('insurance', 'Insurance'), ('internal', 'Internal')], default='internal', max_length=20)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('on_hold', 'On Hold'), ('review', 'Review')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('problem_category', models.CharField(blank=True, max_length=200)),
                ('sub_problem', models.CharField(blank=True, max_length=200)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(db_index=True, default=False)),
                ('sla_breach_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='departments.department')),
            ],
            options={
                'db_table': 'core.tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_system', models.CharField(blank=True, max_length=200)),
                ('business_impact', models.CharField(blank=True, max_length=500)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_fields', to='tickets.ticket')),
            ],
            options={
                'db_table': 'core.internal_fields',
            },
        ),
        migrations.CreateModel(
            name='InsuranceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('insurer_name', models.CharField(blank=True, max_length=200)),
                ('insurer_contact', models.CharField(blank=True, max_length=200)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_fields', to='tickets.ticket')),
            ],
            options={
                'db_table': 'core.insurance_fields',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'core.attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='core.ticket_status_4bfbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status'], name='core.ticket_departm_048add_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status'], name='core.ticket_assigne_06c95f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by'], name='core.ticket_created_dbe699_idx'),
        ),
    ]
