# Generated by Django 6.0.6 on 2026-07-03 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_priority', models.CharField(blank=True, max_length=20)),
                ('priority_reason', models.CharField(blank=True, max_length=300)),
                ('suggested_category', models.CharField(blank=True, max_length=100)),
                ('category_reason', models.CharField(blank=True, max_length=300)),
                ('suggested_tags', models.JSONField(default=list)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('prompt_version', models.CharField(default='v1.0', max_length=20)),
                ('used_fallback', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_cache', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ai.analysis_cache',
            },
        ),
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('feedback_type', models.CharField(choices=[('priority_wrong', 'Priority Wrong'), ('category_wrong', 'Category Wrong'), ('summary_wrong', 'Summary Wrong'), ('resolution_poor', 'Resolution Poor'), ('helpful', 'Helpful')], default='helpful', max_length=30)),
                ('ai_suggestion', models.CharField(max_length=500)),
                ('user_choice', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ai.training_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('feature', models.CharField(max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai.request_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai.request__user_id_c3e902_idx'), models.Index(fields=['feature', 'created_at'], name='ai.request__feature_bb9baf_idx')],
            },
        ),
    ]
