# Generated by Django 6.0.6 on 2026-07-03 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assign', 'Assigned'), ('status_change', 'Status Changed'), ('resolve', 'Resolved'), ('close', 'Closed'), ('escalate', 'Escalated'), ('reopen', 'Reopened'), ('comment', 'Comment Added'), ('attachment', 'Attachment Added'), ('priority_change', 'Priority Changed'), ('update', 'Updated')], max_length=30)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'audit.audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
